indent = 2
margin = 110
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_use_return = true
whitespace_in_kwargs = true
format_docstrings = true
conditional_to_if = true
separate_kwargs_with_semicolon = true
always_for_in = true
for_in_replacement = "∈"

short_to_long_function_def = true
long_to_short_function_def = true